---
title: Can I use the "Super Master/Slave" feature with other DNS servers?
category: 18
frontpage: false
comments: true
created-utc: 2019-01-01
modified-utc: 2019-01-01
---
<div>Simple DNS Plus&nbsp;&quot;super master&quot; and &quot;super slave&quot; servers synchronize their&nbsp;zone lists using an automatically updated &quot;_zonelist&quot; zone - containing one&nbsp;record for each zone.</div>

<div>&nbsp;</div>

<div>It is possible to &quot;fake&quot; a super master&nbsp;with&nbsp;a 3rd party DNS server by&nbsp;creating a &quot;_zonelist&quot; zone, and adding a PTR-record for each zone that you wish to sync in this. The name&nbsp;of each&nbsp;PTR-record should&nbsp;be &quot;_zonelist&quot;, &nbsp;and each PTR-record must&nbsp;point to a unique zone name.<br />
Obviously you will need to keep the &quot;_zonelist&quot; zone updated manually (Simple DNS Plus super masters do this automatically when you add/delete zones).</div>

<div>&nbsp;</div>

<div>Note that this is a bit different from the records in a &quot;_zonelist&quot; zone automatically generated by a Simple DNS Plus super master. Those&nbsp;records also contain the current SOA serial number and suspension status for each zone&nbsp;(special&nbsp;NULL record which cannot be faked in a normal DNS zone).</div>

<div>So &quot;faking&quot; a super master is not as efficient - but it works.</div>

<div>&nbsp;</div>

<div>It is not really possible to &quot;fake&quot; a super slave, as 3rd party&nbsp;DNS servers would not know what to do with the &quot;_zonelist&quot; zone.</div>